#!/usr/bin/env python3
"""Write site/assets/styles/custom.css: chroma styles for both themes.

hugo-book overrides its own custom.css with the site's, and picks dark
either from data-theme="dark" or from the reader's browser when the
theme is "auto".  A chroma stylesheet knows nothing about that, so the
light one is emitted as it comes and the dark one is emitted twice,
each rule under the selector that turns it on.

    make highlight-css
"""

import pathlib
import subprocess
import sys

LIGHT = "github"
DARK = "github-dark"
# Matches "dark" and "contrast-dark" both.
DARK_SCOPES = [':root[data-theme$="dark"]']
AUTO_SCOPE = ':root[data-theme="auto"]'
OUT = pathlib.Path(__file__).parent / "assets" / "styles" / "custom.css"


def chroma(style):
    """The stylesheet Hugo generates for STYLE, its own banner dropped."""
    css = subprocess.run(
        ["hugo", "gen", "chromastyles", "--style", style],
        capture_output=True, text=True, check=True).stdout
    return [line for line in css.splitlines()
            if line.strip() and not line.startswith("/* Generated")]


def scope(lines, prefix):
    """LINES with PREFIX put in front of every selector in them.

    A line is `/* Name */ .selector { ... }`, so the split is at the
    first dot after the comment Hugo writes for the token type.
    """
    out = []
    for line in lines:
        head, _, rule = line.partition("*/ ")
        if not rule:
            head, rule = "", line
        else:
            head += "*/ "
        out.append(f"{head}{prefix} {rule.lstrip()}")
    return out


def main():
    light, dark = chroma(LIGHT), chroma(DARK)
    parts = [
        f"/* Generated by site/gen-highlight-css.py: {LIGHT} and {DARK}.",
        "   Do not edit; run `make highlight-css'. */",
        "",
        f"/* {LIGHT} */",
        *light,
        "",
        f"/* {DARK}, when the reader asked for it */",
        *[line for s in DARK_SCOPES for line in scope(dark, s)],
        "",
        f"/* {DARK}, when the reader's browser asks for it */",
        "@media (prefers-color-scheme: dark) {",
        *scope(dark, AUTO_SCOPE),
        "}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}", file=sys.stderr)


if __name__ == "__main__":
    main()
